# -*- coding: utf-8 -*-
"""PCA Algorithm.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1D41oXYEw3wSUiROBpheslnSkEQiusgDN
"""

def mean_center(matrix):
    """Subtracts the mean of each column from the data."""
    n_rows = len(matrix)
    n_cols = len(matrix[0])


    column_means = [sum(matrix[r][c] for r in range(n_rows)) / n_rows for c in range(n_cols)]

    centered = []
    for r in range(n_rows):
        row = [matrix[r][c] - column_means[c] for c in range(n_cols)]
        centered.append(row)
    return centered, column_means

def transpose(matrix):
    return [[matrix[r][c] for r in range(len(matrix))] for c in range(len(matrix[0]))]

def matmul(A, B):
    if not isinstance(B[0], list):
        return [sum(A[r][c] * B[c] for c in range(len(B))) for r in range(len(A))]

    result = [[0] * len(B[0]) for _ in range(len(A))]
    for i in range(len(A)):
        for j in range(len(B[0])):
            for k in range(len(B)):
                result[i][j] += A[i][k] * B[k][j]
    return result

def covariance_matrix(X_centered):
    n_rows = len(X_centered)
    n_cols = len(X_centered[0])

    cov = [[0.0] * n_cols for _ in range(n_cols)]

    for i in range(n_cols):
        for j in range(n_cols):
            total = sum(X_centered[r][i] * X_centered[r][j] for r in range(n_rows))
            cov[i][j] = total / (n_rows - 1)
    return cov


def power_iteration(A, num_simulations=100):
    """
    Finds the dominant eigenvector (largest eigenvalue) of matrix A.
    """
    n = len(A)
    b_k = [1.0] * n

    for _ in range(num_simulations):
        b_k1 = matmul(A, b_k)

        magnitude = sum(x**2 for x in b_k1) ** 0.5

        b_k = [x / magnitude for x in b_k1]

    return b_k

def deflate_matrix(A, eigenvector):
    n = len(A)

    outer = [[eigenvector[i] * eigenvector[j] for j in range(n)] for i in range(n)]

    Av = matmul(A, eigenvector)
    eigenvalue = sum(Av[i] * eigenvector[i] for i in range(n))

    for i in range(n):
        for j in range(n):
            A[i][j] -= eigenvalue * outer[i][j]
    return A

def raw_pca(X, n_components):
    X_centered, means = mean_center(X)

    cov = covariance_matrix(X_centered)
    components = []
    cov_copy = [row[:] for row in cov]

    for _ in range(n_components):

        eigenvector = power_iteration(cov_copy)
        components.append(eigenvector)

        cov_copy = deflate_matrix(cov_copy, eigenvector)

    X_reduced = matmul(X_centered, transpose(components))

    return X_reduced

dataset = [
    [2.5, 2.4, 0.5],
    [0.5, 0.7, 0.1],
    [2.2, 2.9, 0.9],
    [1.9, 2.2, 0.4],
    [3.1, 3.0, 0.8]
]

reduced_dataset = raw_pca(dataset, n_components=2)

print("Data 2D: ", [round(x, 4) for x in reduced_dataset[0]])